### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Marymota**
another change of syntax but same solution

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @Marymota, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @Marymota! You're now able to merge the PR.

**Comment by Marymota** [comment]
Added a onError event that changed the src to a new target.
It solved the problem but didn't pass the tests.
So I added an if statement that changes the value of item.image.
Also added the prettier configurations to pass the formatting test.

Altered pages:
frontend/src/Item/index.js
frontend/src/ItemPreview.js

**Pull request merged**
